age = input("What is your age? ")
city = input("What city are you from? ")
gender = input("What is your gender? ")
education = input("What type of education did you finish last? (middle school, high school, college, masters, PhD, etc.) ")
pets = input("Do you own pets? ")